seoanalyza/seoanalyza/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from website import views

urlpatterns = [
    url(r'', include('website.urls')),
    path('admin/', admin.site.urls),
    url(r'dash/', include('user_dashboard.urls')),


]

seoanalyza/user_dashboard/urls.py
from django.conf.urls import url
from django.urls import path

from django.contrib.auth import views as auth_views

from user_dashboard import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/dash/login'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

seoanalyza/website/urls.py
from django.conf.urls import url


from website import views
app_name = "website"
urlpatterns = [
    url(r'^$', views.home, name='home')
]

seoanalyza/user_dashboard/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.


from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    email_confirmed = models.BooleanField(default=False)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

seoanalyza/website/models.py
from django.db import models

# Create your models here.

seoanalyza/user_dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    website = forms.CharField()
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

seoanalyza/user_dashboard/views.py
# Create your views here.
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.encoding import force_text, force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from user_dashboard.forms import SignUpForm
from user_dashboard.tokens import account_activation_token


@login_required(login_url='/dash/login/')
def index(request):
    return render(request, 'user_dashboard/index.html')


def user_login(request):
    if request.method == 'GET':
        template = 'user_dashboard/login.html'
        context = {}
        next = request.GET.get('next', None)
        if next:
            context['next'] = next
        return render(request, template, context)
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/dash/')
            else:
                return render(request, 'user_dashboard/login.html', {'error': 'User is not active'})
        else:
            return render(request, 'user_dashboard/login.html', {'error': 'Wrong credentials'})
    else:
        return render(request, 'user_dashboard/login.html', {'error': 'User is not active'})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your analyzaseo.cz account.'
            message = render_to_string('user_dashboard/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the website')
    else:
        form = SignUpForm()
    return render(request, 'user_dashboard/signup.html', {'form': form})


def account_activation_sent(request):
    return render(request, 'user_dashboard/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
        return render(request, 'user_dashboard/activated_user.html')
    else:
        return HttpResponse('Activation link is invalid!')

seoanalyza/website/views.py
# Create your views here.


from django.shortcuts import render



def home(request):
    return render(request, 'website/home.html')

seoanalyza/user_dashboard/templates/user_dashboard/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'dashboard:activate' uidb64=uid token=token %}
{% endautoescape %}

seoanalyza/user_dashboard/templates/user_dashboard/account_activation_invalid.html
{% extends 'website:base.html' %}

{% block content %}
  <p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

seoanalyza/user_dashboard/templates/user_dashboard/account_activation_sent.html
{% extends 'website:base.html' %}

{% block content %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

seoanalyza/user_dashboard/templates/user_dashboard/activated_user.html
{% block content %}
<p>Thank you for your email confirmation. Now you can login your account.</p>
<a href="{% url 'dashboard:login' %}">Go to login page</a>
{% endblock %}

seoanalyza/user_dashboard/templates/user_dashboard/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simple Sidebar - Start Bootstrap Template</title>

    {% load staticfiles %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% bootstrap_messages %}


    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'user_dashboard/css/simple-sidebar.css' %}" />

</head>

<body>

    <div id="wrapper" class="toggled">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <h3 style="color: white">SEO ANALYZA</h3>
                </li>
                <li>
                    <a href="#">Overview</a>
                </li>
                <li>
                    <a href="#">Payments</a>
                </li>
                <li>
                    <a href="/dash/logout">Logout</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <h1>Simple Sidebar</h1>
                <p>This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.</p>
                <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>
                <!--<a href="#menu-toggle" class="btn btn-secondary" id="menu-toggle">Toggle Menu</a>-->
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->


    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>

seoanalyza/user_dashboard/templates/user_dashboard/login.html
{% load staticfiles %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}
{% block content %}
 <div class="container">
      <div class="row">
        <div class="offset-sm-4 col-sm-4">
          <h2>Log in</h2>
          <form class="form-signin" action="{% url 'dashboard:login' %}" method="post" id="login-form">{% csrf_token %}
            <h2 class="form-signin-heading">{{ message }}</h2>
            <label for="id_username" class="sr-only">Email address</label>
            <input type="text" name="username" id="id_username" class="form-control" placeholder="User Name" required autofocus>
            <label for="id_password" class="sr-only">Password</label>
            <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
            <div class="checkbox">
              <label>
                <input type="checkbox" value="remember-me"> Remember me
              </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
          </form>
          {{error}}
        </div>
      </div>
    </div> <!-- /container -->
{% endblock %}

seoanalyza/user_dashboard/templates/user_dashboard/signup.html
{% load staticfiles %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}
<div class="container">
  <div class="row ">
    {% block content %}
    <div class="offset-sm-4 col-sm-4">
      <h2 class="form-signin-heading">Sign up</h2>
      <form class="form-signup" method="post" class="form">
        {% csrf_token %}
          {% for field in form %}
          <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% if field.help_text %}
              <small style="display: none">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
          {% endfor %}

        <button type="submit" class="btn btn-primary btn-block">Sign up</button>
      </form>
    </div>

    {% endblock %}
  </div>
</div>

seoanalyza/website/templates/website/base.html
<html>
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}Analýza SEO{% endblock %}</title>
    {% load staticfiles %}
    {% block head %}{% endblock %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% bootstrap_messages %}
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/styles.css' %}" />
  </head>
  <body>
    {% block menu %}
    <nav class="navbar navbar-expand navbar-light bg-light fixed-top">
      <div class="container">
        <!-- Header -->
        <a href="{% url 'website:home' %}" class="navbar-brand">
          <img width="120px" src="https://seoanalyza.cz/wp-content/uploads/2017/03/SEO_ANALÝZA.png" class="d-inline-block align-top img-responsive">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'website:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#features">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#pricing">Pricing</a>
            </li>
          </ul>
        </div>

        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:signup' %}">Register</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="content">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <img class="d-block img-fluid" style="width: 100%" src="/static/website/images/slide1.png" alt="First slide">
        </div>
        <div class="carousel-item">
          <img class="d-block img-fluid" style="width: 100%" src="/static/website/images/slide1.png" alt="Second slide">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
</div>
    {% block content %}{% endblock %}
    {% endblock %}
    </div>

  </body>
</html>

seoanalyza/website/templates/website/home.html
{% extends 'website/base.html' %}
{% load staticfiles %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'registration/css/styles.css' %}" />
{% endblock %}
{% block content %}

  <div class="container content">
    <div id="home" class="row">
      <div class="col-sm">
        <h5>Denní měření dosažených pozic ve full textu</h5>
        <p>
          Denně pro Vás měříme desítky tisíc slov ve vyhledávačích jako je Seznam.cz a google.cz. Zjistěte i vy, na kterých pozicích se nachází Vaše stránky
        </p>
      </div>

      <div class="col-sm">
        <h5>Denní měření dosažených pozic ve full textu</h5>
        <p>
          Denně pro Vás měříme desítky tisíc slov ve vyhledávačích jako je Seznam.cz a google.cz. Zjistěte i vy, na kterých pozicích se nachází Vaše stránky
        </p>
      </div>

      <div class="col-sm">
        <h5>Denní měření dosažených pozic ve full textu</h5>
        <p>
          Denně pro Vás měříme desítky tisíc slov ve vyhledávačích jako je Seznam.cz a google.cz. Zjistěte i vy, na kterých pozicích se nachází Vaše stránky
        </p>
      </div>
    </div>
    <div id="features">
      <div class="row section">
        <h4>Features</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus rutrum massa magna, et ornare odio vehicula sit amet. Suspendisse a neque porttitor, volutpat lacus sit amet, tristique odio. Vestibulum nec porttitor lectus. Aliquam scelerisque, diam id fringilla sollicitudin, nunc augue pretium nisl, id gravida ligula enim tempor neque. Donec gravida diam nec felis auctor hendrerit. Vestibulum suscipit ligula vitae est egestas pharetra. Suspendisse vel turpis feugiat, sollicitudin nisl id, luctus ex. Quisque fringilla risus elementum leo suscipit volutpat. Ut sollicitudin sit amet eros non porta. Aenean hendrerit magna augue, in sodales mi dignissim vitae.

  Vestibulum finibus congue tortor, sed malesuada magna tincidunt ut. Vivamus scelerisque justo nec tristique varius. Praesent ac risus sed neque dictum congue. Etiam et metus vitae sem scelerisque feugiat quis et augue. Fusce ultricies tellus non risus bibendum aliquet. Pellentesque eu metus risus. Pellentesque posuere bibendum turpis sit amet fermentum. Nam at elit ut tortor blandit pellentesque. Donec sed metus et mauris rhoncus pharetra. Proin varius, augue non vulputate commodo, purus orci pellentesque arcu, sit amet semper dui odio non libero. Quisque mi libero, aliquam et metus ut, molestie luctus erat. Maecenas aliquam quam quis orci euismod, vel facilisis est consequat.

  Vivamus vestibulum turpis ut nisl hendrerit posuere. Cras imperdiet ut est at tempus. Sed porta venenatis fringilla. Nullam tempor nunc quis est posuere, id porta velit condimentum. Vestibulum nec risus venenatis, iaculis tellus quis, laoreet est. Vivamus faucibus neque non est vulputate, et tempor arcu pretium. Praesent erat metus, ullamcorper non dictum sed, interdum gravida est.

  Etiam ac nunc vitae nisi dapibus blandit. Nunc euismod vestibulum mauris, sit amet tempus arcu. Donec quis tempor magna, fringilla mattis urna. Quisque sollicitudin rhoncus nisi, eget luctus leo elementum convallis. Nulla facilisi. Aliquam erat volutpat. Nam lobortis facilisis libero sed aliquet. Integer malesuada purus vitae eros cursus, finibus porttitor est varius. Sed nec tortor maximus, porttitor ex sed, porta leo. Nulla venenatis, sem eu condimentum commodo, est nibh facilisis turpis, eget congue dui ante vel metus. Aenean ut consectetur ex, in vehicula nunc. Aenean mollis tristique dapibus. Nunc metus justo, commodo ut quam quis, pretium iaculis tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et tortor vel nulla ultricies semper. Pellentesque egestas lacus at elit interdum maximus.

  Praesent a imperdiet nulla. Nullam massa elit, rutrum sit amet libero tristique, consequat convallis orci. Nullam eget commodo elit, at fringilla arcu. Curabitur sollicitudin aliquet cursus. Ut auctor lectus leo, vitae tincidunt libero dignissim fringilla. Duis suscipit magna eget nibh placerat, ac euismod nisi imperdiet. Phasellus rutrum aliquam lectus, eget blandit urna semper ut. Suspendisse potenti.</p>
      </div>

    </div>

    <div id="pricing">
      <div class="row section">
        <h4>Pricing</h4>
      </div>
      <div class="row">
        <div class="col-sm">
        <h5>Denní měření dosažených pozic ve full textu</h5>
        <p>
          Denně pro Vás měříme desítky tisíc slov ve vyhledávačích jako je Seznam.cz a google.cz. Zjistěte i vy, na kterých pozicích se nachází Vaše stránky
        </p>
      </div>

      <div class="col-sm">
        <h5>Denní měření dosažených pozic ve full textu</h5>
        <p>
          Denně pro Vás měříme desítky tisíc slov ve vyhledávačích jako je Seznam.cz a google.cz. Zjistěte i vy, na kterých pozicích se nachází Vaše stránky
        </p>
      </div>

      <div class="col-sm">
        <h5>Denní měření dosažených pozic ve full textu</h5>
        <p>
          Denně pro Vás měříme desítky tisíc slov ve vyhledávačích jako je Seznam.cz a google.cz. Zjistěte i vy, na kterých pozicích se nachází Vaše stránky
        </p>
      </div>
    </div>
  </div>
</div>


{% endblock %}